export declare type strictAiSeverityLevel = 0 | 1 | 2 | 3 | 4;
export declare type pinoSeverityLevel = 10 | 20 | 30 | 40 | 50 | 60;
declare type NextLoggerNames = 'console' | 'next.js' | 'Error';
/**
 * Generated by pino inside of next-logger, I think
 */
export declare type LogItem = {
    level: pinoSeverityLevel;
    time: number;
    pid: number;
    hostname: string;
    name: NextLoggerNames;
    msg: string;
    /** speculating, need to verify.. */
    stack?: string;
};
export interface ExceptionItem extends LogItem {
    message: string;
    stack: string;
}
export declare type streamInputData = Array<LogItem>;
export declare type SeverityLevelNames = keyof typeof import('applicationinsights').Contracts.SeverityLevel;
export {};
